blueprint:
  name: "Single awtrix"
  description: "Single awtrix"
  domain: automation
  input:
    awtrix:
      name: AWTRIX Light
      description: Select the Awtrix light
      selector:
        device:
          integration: mqtt
          manufacturer: Blueforcer
          model: AWTRIX Light
          multiple: false
    message:
      name: Message
      description: Message to send to the devices.
      selector:
        text:
variables:
  message: !input message
  device_id: !input awtrix
  device_topic: >-
     {{ expand(device_entities(device_id)) | select('search', 'device_topic') | map(attribute='state') | first }}

trigger:
  - platform: time_pattern
    minutes: /1
condition: []

action:
  - service: mqtt.publish
    data:
      topic: "{{ device_topic ~ '/dev17'}}"
      payload: |-
        {   
          "text": "{{ device_topic }}"
        }

mode: single
