blueprint:
  name: "Clock face awtrix"
  description: "Clock face awtrix"
  domain: automation
  input:
    awtrix:
      name: AWTRIX Light
      description: Select the Awtrix light
      selector:
        device:
          integration: mqtt
          manufacturer: Blueforcer
          model: AWTRIX Light
          multiple: true
    weekday_marker_bar_position:
      name: Where should the weekday bar be positioned?
      description: >
        Where should the weekday bar be positioned?
      selector:
        select:
          options:
            - label: Don't show the weekday bar
              value: never
            - label: Show the weekday on top of the time
              value: top
            - label: Show the weekday on bottom of the time
              value: bottom
      default: "bottom"
    color_current_weekday_marker:
      name: Text Color for the current weekday marker
      description: Select the Text color
      selector:
        color_rgb:
      default: [255, 255, 255]
    color_weekday_marker:
      name: Text Color for the weekday marker
      description: Select the Text color
      selector:
        color_rgb:
      default: [69, 69, 69]
    color_weekday_number:
      name: Text Color for the weekday number
      description: Select the Text color
      selector:
        color_rgb:
      default: [0, 0, 0]
    color_time:
      name: Text Color for the time
      description: Select the Text color
      selector:
        color_rgb:
      default: [255, 255, 255]
    color_top_calendar:
      name: Text Color for the top part of the calendar
      description: Select the Text color
      selector:
        color_rgb:
      default: [255, 0, 0]
    color_bottom_calendar:
      name: Text Color for the top part of the calendar
      description: Select the Text color
      selector:
        color_rgb:
      default: [255, 255, 255]
variables:
  device_ids: !input awtrix
  marker_color_current: !input color_current_weekday_marker
  marker_color: !input color_weekday_marker
  weekday_color: !input color_weekday_number
  time_color: !input color_time
  top_calendar_color: !input color_top_calendar
  bottom_calendar_color: !input color_bottom_calendar
  marker_bar_position: !input weekday_marker_bar_position
  awtrix_devices: >-
    {%- set ns = namespace(awtrix = []) -%}
    {%- for device_id in device_ids -%}
      {%- set device_name = iif(device_attr(device_id, 'name_by_user') != none, device_attr(device_id, 'name_by_user'), device_attr(device_id, 'name')) -%}
      {%- set entity = expand(device_entities(device_id)) | select('search', 'device_topic') | map(attribute='entity_id') | first -%}
      {%- set topic = states(entity) -%}
      {% set ns.awtrix = ns.awtrix + [{"device": device_name, "entity": entity, "topic": topic}] -%}
    {%- endfor -%}
    {{ ns.awtrix }}
  payload: >-
    {% set time = now().strftime("%H:%M") %}
    {% set weekday = now().strftime("%w") %}
    {% set day = now().day %}
    {% set gen_weekday_start = 10 + (weekday|int-1)*3 %}
    {% set gen_weekday_end = 11 + (weekday|int-1)*3 %}
    {% if marker_bar_position == "never" %}
        {% set marker_bar_pos = 0 %}
        {% set clock_pos = 1 %}
    {% elif marker_bar_position == "top" %}
        {% set marker_bar_pos = 0 %}
        {% set clock_pos = 2 %}
    {% elif marker_bar_position == "bottom" %}
        {% set marker_bar_pos = 7 %}
        {% set clock_pos = 1 %}
    {% endif %}
    {
      "stack":false,
      "draw":[
        {% if not marker_bar_position == "never" %}
          {"dl": [10,{{ marker_bar_pos }},11,{{ marker_bar_pos }}, {{ marker_color }}]},
          {"dl": [13,{{ marker_bar_pos }},14,{{ marker_bar_pos }}, {{ marker_color }}]},
          {"dl": [16,{{ marker_bar_pos }},17,{{ marker_bar_pos }}, {{ marker_color }}]},
          {"dl": [19,{{ marker_bar_pos }},20,{{ marker_bar_pos }}, {{ marker_color }}]},
          {"dl": [22,{{ marker_bar_pos }},23,{{ marker_bar_pos }}, {{ marker_color }}]},
          {"dl": [25,{{ marker_bar_pos }},26,{{ marker_bar_pos }}, {{ marker_color }}]},
          {"dl": [28,{{ marker_bar_pos }},29,{{ marker_bar_pos }}, {{ marker_color }}]},
          {"dl": [{{ gen_weekday_start }},{{ marker_bar_pos }},{{ gen_weekday_end }},{{ marker_bar_pos }}, {{ marker_color_current }}]},
        {% endif %}
          {"df": [0,2,9,7,{{ bottom_calendar_color }}]},
          {"df": [0,0,9,2,{{ top_calendar_color }}]},
          {"dt": [1,2,{{ day }},{{ weekday_color }}]},
          {"dt": [11,{{ clock_pos }},"{{ time }}",{{ time_color }}]}
        ],
      "pos":1
    }
trigger:
  - platform: time_pattern
    minutes: /1
condition: []

action:
  - repeat:
      for_each: "{{ awtrix_devices }}"
      sequence:
        - choose:
            - conditions:
                - condition: template
                  value_template: >
                    {{ states(repeat.item.entity) not in ['unavailable', 'unknown'] }}
              sequence:
                - service: mqtt.publish
                  data:
                    qos: 0
                    retain: false
                    topic: "{{ repeat.item.topic }}/notify"
                    payload: "{{ payload }}"

mode: single
