blueprint:
  name: Awtrix Reboot
  description: Reboot Awtrix with the help of a helper
  domain: automation
  author: RobG
  input:
    awtrix:
      name: AWTRIX Light
      description: Select the Awtrix light
      selector:
        device:
          filter:
            - integration: mqtt
              manufacturer: Blueforcer
              model: AWTRIX Light
          multiple: false
    reboot_helper:
      name: Reboot input_button Helper
      description: Select the reboot Helper.
      selector:
        entity:
          filter:
            - domain: input_button

mode: queued

trigger:
  - platform: state
    entity_id: !input reboot_helper

variables:
  device_id: !input awtrix
  awtrix_topic: >-
    {{ expand(device_entities(device_id)) | select('search', 'device_topic') | map(attribute='state') | first }}

action:
  - service: mqtt.publish
    data:
      qos: 0
      retain: false
      topic: "{{ awtrix_topic }}/reboot"
