blueprint:
  name: "Single awtrix"
  description: "Single awtrix"
  domain: automation
  input:
    awtrix:
      name: AWTRIX Light
      description: Select the Awtrix light
      selector:
        device:
          integration: mqtt
          manufacturer: Blueforcer
          model: AWTRIX Light
          multiple: false
    message:
      name: Message
      description: Message to send to the devices.
      selector:
        text:
variables:
  message: !input message
  device_id: !input awtrix
  awtrix_topic: >-
    {{ device_entities(device_id) | select('search', 'device_topic') | first }}

trigger:
  - platform: time_pattern
    minutes: /1
condition: []

action:
  - service: mqtt.publish
    data:
      topic: "{{ awtrix_topic ~ '/dev17'}}"
      payload: |-
        {   
          "text": "{{ awtrix_topic }}"
        }

mode: single
